const fs = require('fs');

let share = fs.readFileSync('src/js/share.js', 'utf8');
const oldInstall = `    function install() {\n        if (!document.body || document.querySelector("[data-smurdy-page-share-trigger]")) return;\n        const trigger = document.createElement("button");\n        trigger.type = "button";\n        trigger.dataset.smurdyPageShareTrigger = "";\n        trigger.textContent = "Share";\n        trigger.setAttribute("aria-haspopup", "dialog");\n        trigger.setAttribute("aria-label", "Share this page");\n        mountTrigger(trigger);\n\n        let dialog = null;\n        trigger.addEventListener("click", () => {\n            if (!dialog) dialog = createDialog();\n            void openShareDialog(dialog, trigger);\n        });\n\n        let mountQueued = false;\n        const queueMount = () => {\n            if (mountQueued) return;\n            mountQueued = true;\n            requestAnimationFrame(() => {\n                mountQueued = false;\n                mountTrigger(trigger);\n            });\n        };\n        const observer = new MutationObserver(queueMount);\n        observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ["hidden", "aria-hidden", "style", "class"] });\n        window.addEventListener("resize", queueMount);\n        window.addEventListener("popstate", queueMount);\n        window.addEventListener("hashchange", queueMount);\n    }`;
const newInstall = `    function removeDuplicateTriggers(canonicalTrigger) {\n        document.querySelectorAll("[data-smurdy-page-share-trigger]").forEach(candidate => {\n            if (candidate !== canonicalTrigger) candidate.remove();\n        });\n    }\n\n    function install() {\n        if (!document.body) return;\n\n        const state = window.__smurdyPageShareState || (window.__smurdyPageShareState = {});\n        let trigger = state.trigger;\n        if (!trigger) {\n            trigger = document.querySelector("[data-smurdy-page-share-trigger]") || document.createElement("button");\n            trigger.type = "button";\n            trigger.dataset.smurdyPageShareTrigger = "";\n            trigger.textContent = "Share";\n            trigger.setAttribute("aria-haspopup", "dialog");\n            trigger.setAttribute("aria-label", "Share this page");\n            state.trigger = trigger;\n        }\n\n        removeDuplicateTriggers(trigger);\n        mountTrigger(trigger);\n\n        if (state.wired) return;\n        state.wired = true;\n\n        trigger.addEventListener("click", () => {\n            if (!state.dialog) state.dialog = createDialog();\n            void openShareDialog(state.dialog, trigger);\n        });\n\n        let mountQueued = false;\n        const queueMount = () => {\n            if (mountQueued) return;\n            mountQueued = true;\n            requestAnimationFrame(() => {\n                mountQueued = false;\n                removeDuplicateTriggers(trigger);\n                mountTrigger(trigger);\n            });\n        };\n        state.observer = new MutationObserver(queueMount);\n        state.observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ["hidden", "aria-hidden", "style", "class"] });\n        window.addEventListener("resize", queueMount);\n        window.addEventListener("popstate", queueMount);\n        window.addEventListener("hashchange", queueMount);\n    }`;
if (!share.includes(oldInstall)) throw new Error('Expected share install block not found');
share = share.replace(oldInstall, newInstall);
fs.writeFileSync('src/js/share.js', share);

let apply = fs.readFileSync('tools/apply_sharing.js', 'utf8');
if (!apply.includes('const ASSET_VERSION = "20260910-sharing-3";')) throw new Error('Expected sharing asset version not found');
apply = apply.replace('const ASSET_VERSION = "20260910-sharing-3";', 'const ASSET_VERSION = "20260911-sharing-4";');
fs.writeFileSync('tools/apply_sharing.js', apply);

let tests = fs.readFileSync('tests/sharing.test.js', 'utf8');
if (!tests.includes('share trigger is a global singleton across dynamic quiz remounts')) {
  tests += `\n\ntest("share trigger is a global singleton across dynamic quiz remounts", () => {\n    const source = read("src/js/share.js");\n    assert.match(source, /window\\.__smurdyPageShareState/);\n    assert.match(source, /state\\.trigger/);\n    assert.match(source, /removeDuplicateTriggers\\(trigger\\)/);\n    assert.match(source, /if \\(state\\.wired\\) return/);\n    assert.match(source, /state\\.observer = new MutationObserver/);\n});\n`;
}
tests = tests.replace(/20260910-sharing-3/g, '20260911-sharing-4');
fs.writeFileSync('tests/sharing.test.js', tests);
